package thuchanh02;


import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class B3_PhanSo extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public B3_PhanSo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcpath = new javax.swing.JFileChooser();
        txtPath = new javax.swing.JTextField();
        btnChosePath = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRandom = new javax.swing.JList();
        btnRandom = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listNotNT = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listNT = new javax.swing.JList();
        txtRead = new javax.swing.JButton();
        txtWrite = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnChosePath.setText("Chọn");
        btnChosePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChosePathActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listRandom);

        btnRandom.setText("Random");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listNotNT);

        jScrollPane3.setViewportView(listNT);

        txtRead.setText("Đọc File");
        txtRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReadActionPerformed(evt);
            }
        });

        txtWrite.setText("Đọc phân số và ghi vào File");
        txtWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWriteActionPerformed(evt);
            }
        });

        jLabel1.setText("Phân số ");

        jLabel2.setText("Phân số nguyên tố");

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel3.setText("SL PS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(64, 64, 64)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addGap(21, 21, 21))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtPath)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnChosePath)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRandom)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtWrite)
                            .addGap(18, 18, 18)
                            .addComponent(txtRead)
                            .addGap(18, 18, 18)
                            .addComponent(btnThoat))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChosePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRandom)
                    .addComponent(txtRead)
                    .addComponent(txtWrite)
                    .addComponent(btnThoat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChosePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChosePathActionPerformed
        // TODO add your handling code here:
        this.jcpath.setVisible(true);
        jcpath.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if(this.jcpath.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            try{
                txtPath.setText(jcpath.getSelectedFile().getCanonicalPath());
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_btnChosePathActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        // TODO add your handling code here:
        DefaultListModel viewList=new DefaultListModel();
        //i<Integer.parseInt(txtSoLuong.getText())
        PhanSo arr[] = new PhanSo[100];
        for(int i=0;i<Integer.parseInt(txtSoLuong.getText());i++){
            arr[i] = new PhanSo();
        }
        for(int i=0;i<Integer.parseInt(txtSoLuong.getText());i++){
            viewList.addElement(arr[i].toString());
        }
//        for(int i=0;i<arr.length;i++){
//            arr[i] = new PhanSo();
//        }
//        for(int i=0;i<arr.length;i++){
//            viewList.addElement(arr[i].toString());
//        }
        listRandom.setModel(viewList);
    }//GEN-LAST:event_btnRandomActionPerformed

    private void txtWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWriteActionPerformed
        // TODO add your handling code here:
        try{
            FileWriter file = new FileWriter(txtPath.getText());
            ListModel viewList = listRandom.getModel();
            for(int i=0;i<viewList.getSize();i++){
                file.write(viewList.getElementAt(i).toString()+"\n");
            }
            
            file.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtWriteActionPerformed

    private void txtReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReadActionPerformed
        // TODO add your handling code here:
        try{
            FileReader file = new FileReader(txtPath.getText());
            BufferedReader buffer = new BufferedReader(file);
            
            List<PhanSo> phanSoCrudes = new ArrayList<PhanSo>();
            String line;
            String[] lineSplit;
            while ((line=buffer.readLine()) != null) {
                System.out.println(line);
                lineSplit = line.split(" / ");
                phanSoCrudes.add(new PhanSo(Integer.parseInt(lineSplit[0]),Integer.parseInt(lineSplit[1])));
            }
            file.close();
            
            List<PhanSo> phanSoPrimes = new ArrayList<PhanSo>();
            List<PhanSo> phanSoNotPrimes = new ArrayList<PhanSo>();
            for(int i =0;i<phanSoCrudes.size();i++){
                if(isPrimeNumber(phanSoCrudes.get(i).mauSo)){
                    phanSoPrimes.add(phanSoCrudes.get(i));
                }else{
                    phanSoNotPrimes.add(phanSoCrudes.get(i));
                }
            }
            
            DefaultListModel viewList=new DefaultListModel();
            for(int i=0;i<phanSoPrimes.size();i++){
                viewList.addElement(phanSoPrimes.get(i).toString());
            }
            listNT.setModel(viewList);
            
            viewList=new DefaultListModel();
            for(int i=0;i<phanSoNotPrimes.size();i++){
                viewList.addElement(phanSoNotPrimes.get(i).toString());
            }
            listNotNT.setModel(viewList);
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtReadActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    public class PhanSo{
        private static final int MIN = 1;
        private static final int MAX = 1000;
        
        public int tuSo;
        public int mauSo;
        public PhanSo(int tuSo, int mauSo){
            this.tuSo = tuSo;
            this.mauSo = mauSo;
        }
        public PhanSo(){
            Random rand = new Random();
            int tuSoRandom = rand.nextInt((MAX - MIN) + 1) + MIN;
            int mauSoRandom = rand.nextInt((MAX - MIN) + 1) + MIN;
//            int tuSoRandom = ThreadLocalRandom.current().nextInt(MIN, MAX + 1);
//            int mauSoRandom = ThreadLocalRandom.current().nextInt(MIN, MAX + 1);
            this.tuSo = tuSoRandom;
            this.mauSo = mauSoRandom;
        }
        public String toString(){
            return this.tuSo+" / "+this.mauSo;
        }
    }
    public static boolean isPrimeNumber(int n) {
        // so nguyen n < 2 khong phai la so nguyen to
        if (n < 2) {
            return false;
        }
        // check so nguyen to khi n >= 2
        int squareRoot = (int) Math.sqrt(n);
        for (int i = 2; i <= squareRoot; i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhanSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhanSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhanSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhanSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B3_PhanSo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChosePath;
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JFileChooser jcpath;
    private javax.swing.JList listNT;
    private javax.swing.JList listNotNT;
    private javax.swing.JList listRandom;
    private javax.swing.JTextField txtPath;
    private javax.swing.JButton txtRead;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JButton txtWrite;
    // End of variables declaration//GEN-END:variables
}
